version: '3.8'

services:
  # PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: bm-app-prod
    container_name: bm-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=bm_app
      - DB_USERNAME=bm_user
      - DB_PASSWORD=bm_password
      - REDIS_HOST=redis
    depends_on:
      - mysql
      - redis
    networks:
      - bm-network

  # Nginx Web Server
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx.prod
      args:
        APP_IMAGE: bm-app-prod
    container_name: bm-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - bm-network

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: bm-mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=bm_app
      - MYSQL_USER=bm_user
      - MYSQL_PASSWORD=bm_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - bm-network

  # Redis Cache
  redis:
    image: redis:alpine
    container_name: bm-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - bm-network

  # Queue Worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: bm-worker
    restart: unless-stopped
    working_dir: /var/www/html
    command: php artisan queue:work --sleep=3 --tries=3 --max-time=3600
    volumes:
      - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - mysql
      - redis
    networks:
      - bm-network

volumes:
  mysql_data:
    driver: local

networks:
  bm-network:
    driver: bridge
